Added server start-up routine suitable for Windows x64 environments
danmenzies-jerram/schnack pull request #1
Opened 2019-02-13 11:15 UTC by danmenzies-jerram

2019-02-13 11:48 UTC, DesignyourCode requested changes
For consistency across platforms, it would be better to keep this as one command. Otherwise you run  the risk of duplicating commands in the `package.json`.

I would recommend looking at installing this package, and setting this up to work with the existing server command: https://www.npmjs.com/package/cross-env

2019-02-13 15:55 UTC, danmenzies-jerram commented
Good call, @DesignyourCode. I'll take a look :-)

2019-02-19 17:05 UTC, danmenzies-jerram commented
Added the [cross-env package](https://www.npmjs.com/package/cross-env), @DesignyourCode, and updated the scripts in the `package.json` file to reflect the new config. Works a treat :-)

Would you mind reviewing again?

2019-02-19 17:19 UTC, DesignyourCode approved these changes

2019-02-19 17:27 UTC, merged